import { User, Grievance, Department, Category, SLAPolicy, InstitutionalIssue, SystemNotification, AuditLogEntry } from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr_student_01',
    name: 'AnantRaj',
    email: 'anantraj@institution.edu',
    role: 'student',
    studentId: 'STU-2024-8841',
    department: 'Computer Science & Engineering',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    phone: '+91 98765 43210',
    joinedDate: '2022-08-15',
    status: 'active',
  },
  {
    id: 'usr_authority_01',
    name: 'Dr. Ramesh Sharma',
    email: 'ramesh.sharma@institution.edu',
    role: 'authority',
    department: 'Estate & Campus Facilities',
    designation: 'Chief Facilities Officer & Grievance Chairperson',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    phone: '+91 98123 45678',
    joinedDate: '2018-03-01',
    status: 'active',
  },
  {
    id: 'usr_authority_02',
    name: 'Prof. Arvind Nambiar',
    email: 'arvind.nambiar@institution.edu',
    role: 'authority',
    department: 'Academic Affairs & Examinations',
    designation: 'Associate Dean of Academic Evaluation',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    phone: '+91 98234 56789',
    joinedDate: '2016-07-10',
    status: 'active',
  },
  {
    id: 'usr_admin_01',
    name: 'Sarah Jenkins',
    email: 'sarah.jenkins@institution.edu',
    role: 'admin',
    department: 'Office of the Registrar & Governance',
    designation: 'Institutional Ombudsman & System Administrator',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    phone: '+91 98345 67890',
    joinedDate: '2015-01-20',
    status: 'active',
  },
];

export const INITIAL_DEPARTMENTS: Department[] = [
  {
    id: 'dept_facilities',
    name: 'Estate & Campus Facilities',
    code: 'ESTATE',
    headName: 'Dr. Ramesh Sharma',
    headEmail: 'ramesh.sharma@institution.edu',
    activeCaseload: 5,
    targetResolutionHours: 48,
    slaComplianceRate: 94.2,
    status: 'active',
  },
  {
    id: 'dept_academic',
    name: 'Academic Affairs & Evaluations',
    code: 'ACAD',
    headName: 'Prof. Arvind Nambiar',
    headEmail: 'arvind.nambiar@institution.edu',
    activeCaseload: 4,
    targetResolutionHours: 72,
    slaComplianceRate: 91.5,
    status: 'active',
  },
  {
    id: 'dept_it',
    name: 'IT Infrastructure & Digital Services',
    code: 'ITSERV',
    headName: 'Vikramaditya Roy',
    headEmail: 'vikram.roy@institution.edu',
    activeCaseload: 6,
    targetResolutionHours: 24,
    slaComplianceRate: 88.7,
    status: 'active',
  },
  {
    id: 'dept_hostel',
    name: 'Hostel Administration & Dining',
    code: 'HOSTEL',
    headName: 'Col. Sanjeev Bakshi (Retd.)',
    headEmail: 'sanjeev.bakshi@institution.edu',
    activeCaseload: 3,
    targetResolutionHours: 36,
    slaComplianceRate: 96.0,
    status: 'active',
  },
  {
    id: 'dept_library',
    name: 'Central Library & Learning Resources',
    code: 'LIB',
    headName: 'Dr. Meenakshi Sundaram',
    headEmail: 'meenakshi.s@institution.edu',
    activeCaseload: 2,
    targetResolutionHours: 48,
    slaComplianceRate: 98.4,
    status: 'active',
  },
  {
    id: 'dept_finance',
    name: 'Finance & Student Accounts',
    code: 'FIN',
    headName: 'Rajeshwari Iyer',
    headEmail: 'rajeshwari.iyer@institution.edu',
    activeCaseload: 2,
    targetResolutionHours: 96,
    slaComplianceRate: 89.1,
    status: 'active',
  },
];

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat_facilities',
    name: 'Estate & Campus Facilities',
    departmentId: 'dept_facilities',
    departmentName: 'Estate & Campus Facilities',
    subcategories: ['HVAC & Air Conditioning', 'Plumbing & Water Supply', 'Electrical & Lighting', 'Classroom Furniture', 'Elevators & Escalators'],
    defaultPriority: 'HIGH',
    slaHours: 48,
  },
  {
    id: 'cat_academic',
    name: 'Academic Affairs',
    departmentId: 'dept_academic',
    departmentName: 'Academic Affairs & Evaluations',
    subcategories: ['Grade Discrepancy', 'Course Registration', 'Faculty Attendance & Conduct', 'Exam Timetable Clash', 'Thesis Evaluation Delay'],
    defaultPriority: 'MEDIUM',
    slaHours: 72,
  },
  {
    id: 'cat_it',
    name: 'IT & Digital Services',
    departmentId: 'dept_it',
    departmentName: 'IT Infrastructure & Digital Services',
    subcategories: ['Wi-Fi / LAN Downtime', 'Student Portal / ERP Bugs', 'Lab Workstation Failure', 'Email / SSO Account Access', 'Software License Access'],
    defaultPriority: 'HIGH',
    slaHours: 24,
  },
  {
    id: 'cat_hostel',
    name: 'Hostel & Residence',
    departmentId: 'dept_hostel',
    departmentName: 'Hostel Administration & Dining',
    subcategories: ['Mess Food Quality & Hygiene', 'Room Allocation & Maintenance', 'Security & Curfew', 'Laundry Equipment', 'Common Room Amenities'],
    defaultPriority: 'MEDIUM',
    slaHours: 36,
  },
  {
    id: 'cat_safety',
    name: 'Campus Safety & Harassment',
    departmentId: 'dept_facilities',
    departmentName: 'Estate & Campus Facilities',
    subcategories: ['Campus Lighting / Dark Zones', 'Ragging / Bullying Incident', 'Theft / Missing Property', 'Emergency Medical Response'],
    defaultPriority: 'CRITICAL',
    slaHours: 12,
  },
];

export const INITIAL_SLA_POLICIES: SLAPolicy[] = [
  {
    id: 'sla_crit',
    priority: 'CRITICAL',
    firstResponseHours: 2,
    resolutionHours: 12,
    autoEscalationHours: 6,
    notificationFrequencyHours: 1,
  },
  {
    id: 'sla_high',
    priority: 'HIGH',
    firstResponseHours: 6,
    resolutionHours: 24,
    autoEscalationHours: 18,
    notificationFrequencyHours: 4,
  },
  {
    id: 'sla_med',
    priority: 'MEDIUM',
    firstResponseHours: 12,
    resolutionHours: 48,
    autoEscalationHours: 36,
    notificationFrequencyHours: 8,
  },
  {
    id: 'sla_low',
    priority: 'LOW',
    firstResponseHours: 24,
    resolutionHours: 96,
    autoEscalationHours: 72,
    notificationFrequencyHours: 24,
  },
];

export const INITIAL_INSTITUTIONAL_ISSUES: InstitutionalIssue[] = [
  {
    id: 'ISSUE-CLUSTER-01',
    title: 'Intermittent Wi-Fi AP Drops Across South Wing Hostels',
    description: 'Multiple students reporting frequent network packet loss and captive portal authentication timeouts in Hostel Block C and D during peak study hours (8 PM - 11 PM).',
    department: 'IT Infrastructure & Digital Services',
    category: 'IT & Digital Services',
    location: 'Hostel Block C & D (Floors 2-4)',
    affectedStudentsCount: 142,
    linkedGrievanceIds: ['GRV-2024-085', 'GRV-2024-091', 'GRV-2024-094'],
    severity: 'HIGH',
    status: 'Mitigation In Progress',
    detectedAt: '2026-08-25T14:30:00Z',
    lastUpdated: '2026-08-29T10:15:00Z',
    recommendedMitigation: 'Core switch firmware upgrade scheduled for Sunday 2 AM. Deploy 4 supplementary dual-band Cisco APs on Block C 3rd floor corridor.',
  },
  {
    id: 'ISSUE-CLUSTER-02',
    title: 'HVAC Condensation & Water Leakage in Advanced Computing Labs',
    description: 'Central air handler coil drip tray overflow causing ceiling moisture and water droplet drops near electrical distribution panels in Lab 401-404.',
    department: 'Estate & Campus Facilities',
    category: 'Estate & Campus Facilities',
    location: 'Academic Complex 4th Floor (Labs 401-404)',
    affectedStudentsCount: 88,
    linkedGrievanceIds: ['GRV-2024-089', 'GRV-2024-098'],
    severity: 'CRITICAL',
    status: 'Investigating',
    detectedAt: '2026-08-28T09:00:00Z',
    lastUpdated: '2026-08-29T16:00:00Z',
    recommendedMitigation: 'Isolate AC line 4B immediately. Deploy maintenance contractor to flush condensate drain line and replace saturated ceiling tiles.',
  },
];

export const INITIAL_GRIEVANCES: Grievance[] = [
  {
    id: 'GRV-2024-089',
    trackingCode: 'TRK-8892-C4',
    title: 'Severe Ceiling Water Leakage Over Workstations in Computing Lab 402',
    description: 'The central AC duct in Computer Lab 402 has been leaking substantial amounts of water since this morning. Droplets are falling directly onto two high-spec PC towers and adjacent power extension boxes, posing an immediate electrical short-circuit hazard during practical sessions.',
    category: 'Estate & Campus Facilities',
    subcategory: 'HVAC & Air Conditioning',
    location: 'Academic Block 4, 4th Floor, Lab 402',
    studentId: 'usr_student_01',
    studentName: 'AnantRaj',
    studentEmail: 'anantraj@institution.edu',
    assignedAuthorityId: 'usr_authority_01',
    assignedAuthorityName: 'Dr. Ramesh Sharma',
    department: 'Estate & Campus Facilities',
    priority: 'CRITICAL',
    status: 'in_progress',
    createdAt: '2026-08-28T08:45:00Z',
    updatedAt: '2026-08-29T14:30:00Z',
    slaDeadline: '2026-08-29T20:45:00Z',
    slaBreached: false,
    aiAnalysis: {
      summary: 'Critical water leakage from ceiling HVAC unit threatening active computer hardware and electrical points in Lab 402.',
      category: 'Estate & Campus Facilities',
      subcategory: 'HVAC & Air Conditioning',
      confidenceScore: 97,
      priority: 'CRITICAL',
      priorityReason: 'Identified active electrical hazard and potential for institution equipment damage in a high-occupancy lab.',
      urgencyScore: 9,
      sentiment: 'Frustrated',
      recommendedDepartment: 'Estate & Campus Facilities',
      routingReason: 'HVAC condensation drainage failure requires urgent estate technician intervention.',
      extractedEntities: [
        { label: 'Location', value: 'Lab 402, Block 4', category: 'location' },
        { label: 'Hazard', value: 'Electrical Short Circuit Risk', category: 'equipment' },
        { label: 'Asset Impacted', value: 'PC Towers & Power Boxes', category: 'equipment' },
      ],
      similarGrievances: [
        {
          id: 'GRV-2024-098',
          title: 'AC Droplets over Server Rack in Lab 401',
          category: 'Estate & Campus Facilities',
          status: 'under_review',
          similarityScore: 88,
          submittedDate: '2026-08-28',
          snippet: 'Similar condensation issue reported in adjacent room Lab 401.',
        }
      ],
      severitySignals: ['Electrical Risk', 'Asset Damage', 'Lab Interruption'],
      suggestedAction: 'Isolate AC line immediately and dispatch emergency plumbing/HVAC repair crew.',
      analyzedAt: '2026-08-28T08:45:15Z',
    },
    attachments: [
      {
        id: 'att_01',
        name: 'lab402_leak_photo.jpg',
        size: '2.4 MB',
        type: 'image/jpeg',
        url: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=600&auto=format&fit=crop&q=80',
        uploadedAt: '2026-08-28T08:45:00Z',
      }
    ],
    comments: [
      {
        id: 'cmt_01',
        authorId: 'usr_authority_01',
        authorName: 'Dr. Ramesh Sharma',
        authorRole: 'authority',
        authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
        content: 'Thank you for reporting AnantRaj. I have instructed the duty electrical supervisor to cordon off rows 3 & 4 and power down the extension circuit while the HVAC team inspects the drain tray.',
        timestamp: '2026-08-28T09:15:00Z',
      },
      {
        id: 'cmt_02',
        authorId: 'usr_student_01',
        authorName: 'AnantRaj',
        authorRole: 'student',
        authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
        content: 'Thank you Dr. Sharma. The power has been turned off safely for those desks.',
        timestamp: '2026-08-28T09:40:00Z',
      }
    ],
    timeline: [
      {
        id: 'tl_01',
        title: 'Grievance Submitted',
        description: 'Case registered by AnantRaj with 1 high-resolution evidence photo.',
        timestamp: '2026-08-28T08:45:00Z',
        actor: 'AnantRaj',
        actorRole: 'student',
        type: 'submission',
      },
      {
        id: 'tl_02',
        title: 'AI Intelligence Triage Completed',
        description: 'Auto-classified with 97% confidence as CRITICAL Estate & Facilities incident.',
        timestamp: '2026-08-28T08:45:15Z',
        actor: 'GrievAI Engine',
        actorRole: 'system',
        type: 'ai_analysis',
      },
      {
        id: 'tl_03',
        title: 'Assigned to Estate Chairperson',
        description: 'Routed automatically to Dr. Ramesh Sharma based on category & severity.',
        timestamp: '2026-08-28T08:50:00Z',
        actor: 'Dr. Ramesh Sharma',
        actorRole: 'authority',
        type: 'assignment',
      },
      {
        id: 'tl_04',
        title: 'Status Updated to In Progress',
        description: 'Maintenance contractor issued emergency work permit #EM-882.',
        timestamp: '2026-08-28T09:15:00Z',
        actor: 'Dr. Ramesh Sharma',
        actorRole: 'authority',
        type: 'status_change',
      }
    ],
    officialDraftResponse: 'Dear AnantRaj,\n\nWe acknowledge the critical nature of the water leakage reported in Lab 402. Our maintenance engineering team has isolated the condensate line and placed a temporary catch basin. Full pipe clearing and tile replacement will occur today between 6:00 PM and 8:00 PM to ensure no lab disruptions tomorrow.\n\nWarm regards,\nDr. Ramesh Sharma\nChairperson, Estate & Facilities',
  },
  {
    id: 'GRV-2024-085',
    trackingCode: 'TRK-7712-W1',
    title: 'Hostel Block C Wi-Fi Frequent Disconnections and High Latency',
    description: 'Every evening between 8 PM and 11 PM, the Wi-Fi access points on 3rd Floor of Hostel Block C drop all connections. The login captive portal repeatedly shows gateway timeout errors, preventing online submissions and research work.',
    category: 'IT & Digital Services',
    subcategory: 'Wi-Fi / LAN Downtime',
    location: 'Hostel Block C, 3rd Floor Corridor',
    studentId: 'usr_student_01',
    studentName: 'AnantRaj',
    studentEmail: 'anantraj@institution.edu',
    assignedAuthorityId: 'usr_authority_01',
    assignedAuthorityName: 'Dr. Ramesh Sharma',
    department: 'IT Infrastructure & Digital Services',
    priority: 'HIGH',
    status: 'under_review',
    createdAt: '2026-08-27T19:20:00Z',
    updatedAt: '2026-08-28T11:00:00Z',
    slaDeadline: '2026-08-28T19:20:00Z',
    slaBreached: true,
    aiAnalysis: {
      summary: 'Recurring peak-hour wireless network congestion and authentication gateway failures in Hostel Block C.',
      category: 'IT & Digital Services',
      subcategory: 'Wi-Fi / LAN Downtime',
      confidenceScore: 94,
      priority: 'HIGH',
      priorityReason: 'Affects multiple resident students during critical evening assignment and study windows.',
      urgencyScore: 7,
      sentiment: 'Negative',
      recommendedDepartment: 'IT Infrastructure & Digital Services',
      routingReason: 'Access point DHCP pool exhaustion and bandwidth throttling issue.',
      extractedEntities: [
        { label: 'Location', value: 'Hostel Block C, Floor 3', category: 'location' },
        { label: 'Time window', value: '8 PM - 11 PM Daily', category: 'date' },
        { label: 'Service', value: 'Captive Portal / Wi-Fi', category: 'equipment' },
      ],
      similarGrievances: [
        {
          id: 'GRV-2024-091',
          title: 'Wi-Fi unreachable in Block C room 314',
          category: 'IT & Digital Services',
          status: 'under_review',
          similarityScore: 92,
          submittedDate: '2026-08-27',
          snippet: 'Student reporting 0% signal strength in room 314 after 9 PM.',
        }
      ],
      severitySignals: ['Mass Disruption', 'SLA Breached', 'Academic Impact'],
      suggestedAction: 'Increase DHCP lease capacity on subnet 10.14.3.0/24 and schedule antenna realignment.',
      analyzedAt: '2026-08-27T19:20:10Z',
    },
    attachments: [],
    comments: [],
    timeline: [
      {
        id: 'tl_85_1',
        title: 'Grievance Submitted',
        description: 'Submitted by AnantRaj.',
        timestamp: '2026-08-27T19:20:00Z',
        actor: 'AnantRaj',
        actorRole: 'student',
        type: 'submission',
      },
      {
        id: 'tl_85_2',
        title: 'AI Analysis Completed',
        description: 'Detected 92% similarity with Case #GRV-2024-091.',
        timestamp: '2026-08-27T19:20:10Z',
        actor: 'GrievAI Engine',
        actorRole: 'system',
        type: 'ai_analysis',
      }
    ],
  },
  {
    id: 'GRV-2024-072',
    trackingCode: 'TRK-5541-L2',
    title: 'Required Core Reference Books Missing from Central Library Reserves',
    description: 'The designated reference text "Distributed Systems: Principles and Paradigms (3rd Ed)" by Tanenbaum is entirely unavailable in the reserve section. Only 2 battered copies exist for 240 enrolled students in CS301.',
    category: 'Academic Affairs',
    subcategory: 'Course Registration & Material',
    location: 'Central Library, 2nd Floor Reserve Desk',
    studentId: 'usr_student_01',
    studentName: 'AnantRaj',
    studentEmail: 'anantraj@institution.edu',
    assignedAuthorityId: 'usr_authority_02',
    assignedAuthorityName: 'Prof. Arvind Nambiar',
    department: 'Central Library & Learning Resources',
    priority: 'MEDIUM',
    status: 'resolved',
    createdAt: '2026-08-15T10:00:00Z',
    updatedAt: '2026-08-18T16:00:00Z',
    slaDeadline: '2026-08-19T10:00:00Z',
    slaBreached: false,
    aiAnalysis: {
      summary: 'Shortage of required textbooks for CS301 course affecting exam preparation.',
      category: 'Academic Affairs',
      subcategory: 'Course Registration & Material',
      confidenceScore: 91,
      priority: 'MEDIUM',
      priorityReason: 'Affects curriculum access; digital licensing alternative feasible.',
      urgencyScore: 5,
      sentiment: 'Neutral',
      recommendedDepartment: 'Central Library & Learning Resources',
      routingReason: 'Library acquisition committee and digital repository manager.',
      extractedEntities: [
        { label: 'Book Title', value: 'Distributed Systems 3rd Ed', category: 'equipment' },
        { label: 'Course Code', value: 'CS301', category: 'course' },
      ],
      similarGrievances: [],
      severitySignals: ['Curriculum Access'],
      suggestedAction: 'Acquire institutional e-book multi-user license and procure 10 physical copies.',
      analyzedAt: '2026-08-15T10:00:12Z',
    },
    attachments: [],
    comments: [
      {
        id: 'cmt_lib_01',
        authorId: 'usr_authority_02',
        authorName: 'Prof. Arvind Nambiar',
        authorRole: 'authority',
        authorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
        content: 'Dear AnantRaj, we have provisioned 250 perpetual digital access seats via IEEE/Springer e-Library and placed an urgent PO for 12 hardcopies in the 24-hr reserve room.',
        timestamp: '2026-08-18T15:45:00Z',
      }
    ],
    timeline: [
      {
        id: 'tl_72_1',
        title: 'Case Submitted',
        description: 'Student submitted book availability grievance.',
        timestamp: '2026-08-15T10:00:00Z',
        actor: 'AnantRaj',
        actorRole: 'student',
        type: 'submission',
      },
      {
        id: 'tl_72_2',
        title: 'Resolved by Academic Dean',
        description: 'E-book institutional access link sent to all CS301 students.',
        timestamp: '2026-08-18T16:00:00Z',
        actor: 'Prof. Arvind Nambiar',
        actorRole: 'authority',
        type: 'resolution',
      },
      {
        id: 'tl_72_3',
        title: 'Feedback Received',
        description: 'Student rated resolution 5 stars.',
        timestamp: '2026-08-19T09:30:00Z',
        actor: 'AnantRaj',
        actorRole: 'student',
        type: 'feedback',
      }
    ],
    feedback: {
      rating: 5,
      tags: ['Prompt Resolution', 'Digital Access Provided', 'Great Communication'],
      feedbackText: 'Very grateful for the immediate e-book link provided before mid-semester exams!',
      submittedAt: '2026-08-19T09:30:00Z',
    },
    resolutionSummary: 'Procured institutional campus-wide digital e-book access for all registered students and placed 12 physical copies in 24-hour reading room.',
    rootCauseCategory: 'Resource Shortage / Enrollment Surge',
  },
  {
    id: 'GRV-2024-061',
    trackingCode: 'TRK-3310-M9',
    title: 'Discrepancy in Midterm Grade Calculation for Advanced Algorithms',
    description: 'My score for Question 4 in Midterm 1 was marked 0 despite matching the official instructor solution rubric. The TA refused to review it during office hours.',
    category: 'Academic Affairs',
    subcategory: 'Grade Discrepancy',
    location: 'Department of Computer Science',
    studentId: 'usr_student_01',
    studentName: 'AnantRaj',
    studentEmail: 'anantraj@institution.edu',
    assignedAuthorityId: 'usr_authority_02',
    assignedAuthorityName: 'Prof. Arvind Nambiar',
    department: 'Academic Affairs & Evaluations',
    priority: 'MEDIUM',
    status: 'resolved',
    createdAt: '2026-08-10T14:15:00Z',
    updatedAt: '2026-08-14T11:20:00Z',
    slaDeadline: '2026-08-13T14:15:00Z',
    slaBreached: false,
    aiAnalysis: {
      summary: 'Student grade verification request for Midterm 1 algorithmic correctness rubric.',
      category: 'Academic Affairs',
      subcategory: 'Grade Discrepancy',
      confidenceScore: 96,
      priority: 'MEDIUM',
      priorityReason: 'Procedural academic re-evaluation request with clear documentation.',
      urgencyScore: 4,
      sentiment: 'Constructive',
      recommendedDepartment: 'Academic Affairs & Evaluations',
      routingReason: 'Course coordinator re-totaling protocol.',
      extractedEntities: [
        { label: 'Course', value: 'CS302 Algorithms', category: 'course' },
        { label: 'Assessment', value: 'Midterm 1, Q4', category: 'date' },
      ],
      similarGrievances: [],
      severitySignals: ['Grading Integrity'],
      suggestedAction: 'Notify Course Instructor to re-verify answer script with student.',
      analyzedAt: '2026-08-10T14:15:10Z',
    },
    attachments: [],
    comments: [],
    timeline: [
      {
        id: 'tl_61_1',
        title: 'Case Filed',
        description: 'Filed with answer sheet copy.',
        timestamp: '2026-08-10T14:15:00Z',
        actor: 'AnantRaj',
        actorRole: 'student',
        type: 'submission',
      },
      {
        id: 'tl_61_2',
        title: 'Re-evaluation Approved',
        description: 'Marks updated from 72/100 to 82/100.',
        timestamp: '2026-08-14T11:20:00Z',
        actor: 'Prof. Arvind Nambiar',
        actorRole: 'authority',
        type: 'resolution',
      }
    ],
    feedback: {
      rating: 5,
      tags: ['Fair Evaluation', 'Quick Review'],
      feedbackText: 'Prof. Nambiar reviewed the paper personally and resolved the discrepancy within days.',
      submittedAt: '2026-08-14T12:00:00Z',
    },
    resolutionSummary: 'Answer script re-checked by Course Lead Instructor. 10 marks awarded as per official solution key.',
    rootCauseCategory: 'Grading Error / TA Oversight',
  },
  {
    id: 'GRV-2024-095',
    trackingCode: 'TRK-9901-S3',
    title: 'Broken Streetlights on South Campus Pathway creating Safety Hazard',
    description: 'Three consecutive solar streetlights along the pathway between Library and Girls Hostel Block B have been non-functional for the past 4 days, resulting in pitch dark areas at night.',
    category: 'Estate & Campus Facilities',
    subcategory: 'Campus Lighting / Dark Zones',
    location: 'South Campus Pathway near Block B',
    studentId: 'usr_student_02',
    studentName: 'Pooja Verma',
    studentEmail: 'pooja.verma@institution.edu',
    assignedAuthorityId: 'usr_authority_01',
    assignedAuthorityName: 'Dr. Ramesh Sharma',
    department: 'Estate & Campus Facilities',
    priority: 'CRITICAL',
    status: 'escalated',
    escalationTier: 2,
    escalationReason: 'Pending contractor battery delivery exceeded 48 hours in critical safety zone.',
    createdAt: '2026-08-26T21:00:00Z',
    updatedAt: '2026-08-29T15:00:00Z',
    slaDeadline: '2026-08-27T09:00:00Z',
    slaBreached: true,
    aiAnalysis: {
      summary: 'Critical campus perimeter safety hazard due to multi-lamp illumination outage near hostel pathway.',
      category: 'Campus Safety & Harassment',
      subcategory: 'Campus Lighting / Dark Zones',
      confidenceScore: 99,
      priority: 'CRITICAL',
      priorityReason: 'High vulnerability night transit zone for female students; immediate safety priority.',
      urgencyScore: 10,
      sentiment: 'Very Negative',
      recommendedDepartment: 'Estate & Campus Facilities',
      routingReason: 'Campus Security and Electrical Maintenance emergency escalation.',
      extractedEntities: [
        { label: 'Location', value: 'South Campus Pathway, Hostel B', category: 'location' },
        { label: 'Risk Factor', value: 'Nighttime Safety & Visibility', category: 'person' },
      ],
      similarGrievances: [],
      severitySignals: ['Perimeter Security', 'Student Safety', 'SLA Critical'],
      suggestedAction: 'Deploy portable floodlights immediately and expedite solar inverter battery replacement.',
      analyzedAt: '2026-08-26T21:00:10Z',
    },
    attachments: [],
    comments: [
      {
        id: 'cmt_95_1',
        authorId: 'usr_authority_01',
        authorName: 'Dr. Ramesh Sharma',
        authorRole: 'authority',
        authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
        content: 'Campus security has deployed 2 motorized patrol guards on this pathway from 7 PM to 6 AM while the electrical team replaces the main underground power cable.',
        timestamp: '2026-08-27T10:00:00Z',
      }
    ],
    timeline: [
      {
        id: 'tl_95_1',
        title: 'Emergency Case Logged',
        description: 'Logged by Pooja Verma.',
        timestamp: '2026-08-26T21:00:00Z',
        actor: 'Pooja Verma',
        actorRole: 'student',
        type: 'submission',
      },
      {
        id: 'tl_95_2',
        title: 'Escalated to Tier 2 Head of Estate',
        description: 'Auto-escalated due to critical safety classification.',
        timestamp: '2026-08-27T09:00:00Z',
        actor: 'GrievAI Engine',
        actorRole: 'system',
        type: 'escalation',
      }
    ],
  },
  {
    id: 'GRV-2024-099',
    trackingCode: 'TRK-1029-F4',
    title: 'Duplicate Hostel Security Deposit Deducted on ERP Portal',
    description: 'During semester fee payment on the online portal, transaction timed out on the first attempt but amount was debited twice (INR 15,000 x 2). Only one receipt was generated.',
    category: 'Finance & Accounts',
    subcategory: 'Fee & Payment Discrepancy',
    location: 'Finance Portal / Online Gateway',
    studentId: 'usr_student_03',
    studentName: 'Rohan Mehra',
    studentEmail: 'rohan.mehra@institution.edu',
    assignedAuthorityId: 'usr_admin_01',
    assignedAuthorityName: 'Sarah Jenkins',
    department: 'Finance & Student Accounts',
    priority: 'HIGH',
    status: 'information_requested',
    infoRequestedText: 'Please upload the official bank statement PDF showing both transaction reference numbers (RRN / UTR) to initiate immediate bank chargeback clearance.',
    createdAt: '2026-08-27T12:30:00Z',
    updatedAt: '2026-08-28T16:00:00Z',
    slaDeadline: '2026-08-30T12:30:00Z',
    slaBreached: false,
    aiAnalysis: {
      summary: 'Payment gateway double-charge error for semester hostel caution deposit.',
      category: 'Finance & Accounts',
      subcategory: 'Fee & Payment Discrepancy',
      confidenceScore: 98,
      priority: 'HIGH',
      priorityReason: 'Financial discrepancy causing financial distress to student.',
      urgencyScore: 8,
      sentiment: 'Frustrated',
      recommendedDepartment: 'Finance & Student Accounts',
      routingReason: 'Accounts reconciliation with payment aggregator gateway.',
      extractedEntities: [
        { label: 'Amount', value: 'INR 15,000 (Duplicate)', category: 'policy' },
        { label: 'Service', value: 'Hostel Caution Deposit', category: 'policy' },
      ],
      similarGrievances: [],
      severitySignals: ['Double Debit', 'Bank Reconciliation Required'],
      suggestedAction: 'Request UTR number from student and trigger automated refund via payment aggregator.',
      analyzedAt: '2026-08-27T12:30:15Z',
    },
    attachments: [],
    comments: [],
    timeline: [
      {
        id: 'tl_99_1',
        title: 'Case Submitted',
        description: 'Submitted by Rohan Mehra.',
        timestamp: '2026-08-27T12:30:00Z',
        actor: 'Rohan Mehra',
        actorRole: 'student',
        type: 'submission',
      },
      {
        id: 'tl_99_2',
        title: 'Information Requested from Student',
        description: 'Authority requested bank statement with UTR numbers.',
        timestamp: '2026-08-28T16:00:00Z',
        actor: 'Sarah Jenkins',
        actorRole: 'authority',
        type: 'status_change',
      }
    ],
  }
];

export const INITIAL_NOTIFICATIONS: SystemNotification[] = [
  {
    id: 'notif_01',
    userId: 'usr_student_01',
    targetRole: 'student',
    title: 'Grievance Update: Lab 402 AC Leakage',
    message: 'Dr. Ramesh Sharma updated status to "In Progress" and scheduled repair work.',
    grievanceId: 'GRV-2024-089',
    type: 'info',
    read: false,
    createdAt: '2026-08-28T09:15:00Z',
    link: '/student/grievance/GRV-2024-089',
  },
  {
    id: 'notif_02',
    userId: 'usr_student_01',
    targetRole: 'student',
    title: 'SLA Warning Alert',
    message: 'Case #GRV-2024-085 (Hostel Wi-Fi) has exceeded normal resolution SLA and was prioritized.',
    grievanceId: 'GRV-2024-085',
    type: 'warning',
    read: false,
    createdAt: '2026-08-28T19:20:00Z',
    link: '/student/grievance/GRV-2024-085',
  },
  {
    id: 'notif_03',
    userId: 'usr_student_01',
    targetRole: 'student',
    title: 'Resolution Completed: Library Books',
    message: 'Prof. Nambiar resolved your request. Please take a moment to rate your experience.',
    grievanceId: 'GRV-2024-072',
    type: 'success',
    read: true,
    createdAt: '2026-08-18T16:00:00Z',
    link: '/student/rate/GRV-2024-072',
  },
  {
    id: 'notif_04',
    userId: 'usr_authority_01',
    targetRole: 'authority',
    title: 'New Critical Triage Assigned',
    message: 'GrievAI auto-routed Case #GRV-2024-089 (Lab 402 Electrical/Water hazard) to your queue.',
    grievanceId: 'GRV-2024-089',
    type: 'alert',
    read: false,
    createdAt: '2026-08-28T08:50:00Z',
    link: '/authority/workspace/GRV-2024-089',
  },
  {
    id: 'notif_05',
    userId: 'usr_admin_01',
    targetRole: 'admin',
    title: 'System Anomaly Detected',
    message: 'Cluster #ISSUE-CLUSTER-01 identified: 142 students impacted by Wi-Fi drops in Block C & D.',
    type: 'alert',
    read: false,
    createdAt: '2026-08-29T10:15:00Z',
    link: '/admin/issues/ISSUE-CLUSTER-01',
  }
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'audit_01',
    timestamp: '2026-08-28T08:45:00Z',
    actorId: 'usr_student_01',
    actorName: 'AnantRaj',
    actorRole: 'student',
    action: 'CREATE_GRIEVANCE',
    grievanceId: 'GRV-2024-089',
    details: 'Submitted case "Severe Ceiling Water Leakage in Lab 402" with 1 attachment.',
    ipAddress: '10.14.88.21',
  },
  {
    id: 'audit_02',
    timestamp: '2026-08-28T08:45:15Z',
    actorId: 'ai_engine',
    actorName: 'GrievAI Autonomous Classifier',
    actorRole: 'system',
    action: 'AI_TRIAGE_COMPLETE',
    grievanceId: 'GRV-2024-089',
    details: 'Classified: Category=Estate & Facilities, Priority=CRITICAL (Confidence: 97%). Auto-assigned to Dr. Ramesh Sharma.',
    ipAddress: 'internal://ai-worker',
  },
  {
    id: 'audit_03',
    timestamp: '2026-08-28T09:15:00Z',
    actorId: 'usr_authority_01',
    actorName: 'Dr. Ramesh Sharma',
    actorRole: 'authority',
    action: 'STATUS_TRANSITION',
    grievanceId: 'GRV-2024-089',
    details: 'Status changed: SUBMITTED -> IN_PROGRESS. Internal repair permit issued.',
    ipAddress: '10.14.2.14',
  },
  {
    id: 'audit_04',
    timestamp: '2026-08-27T19:20:00Z',
    actorId: 'usr_student_01',
    actorName: 'AnantRaj',
    actorRole: 'student',
    action: 'CREATE_GRIEVANCE',
    grievanceId: 'GRV-2024-085',
    details: 'Submitted case "Hostel Block C Wi-Fi Frequent Disconnections".',
    ipAddress: '10.14.3.45',
  },
  {
    id: 'audit_05',
    timestamp: '2026-08-28T19:20:00Z',
    actorId: 'sla_monitor',
    actorName: 'SLA Automated Daemon',
    actorRole: 'system',
    action: 'SLA_BREACH_TRIGGER',
    grievanceId: 'GRV-2024-085',
    details: '24-hour first response window breached for HIGH priority case.',
    ipAddress: 'internal://cron',
  },
];
