"""initial_23_tables

Revision ID: cd1346307e2b
Revises: 
Create Date: 2026-09-04 04:06:44.181523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd1346307e2b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('feedback_satisfaction_rating_check'), 'feedback', type_='check')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(op.f('feedback_satisfaction_rating_check'), 'feedback', 'satisfaction_rating >= 1 AND satisfaction_rating <= 5')
    # ### end Alembic commands ###
